---
# Ansible playbook for a Node.js API app server.
#
# @author Jeff Geerling (2015).

- hosts: all
  gather_facts: yes

  vars_files:
    - vars/main.yml

  tasks:
    - name: Simple Test 
      file:
        path: /root/testdir 
        state: directory    

    - name: install nfs  
      yum:
        pkg: nfs-utils 
