# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "centos/8"
  config.vm.hostname = "workstation.lab.example.com"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  # config.vm.box_check_update = false

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port
  # config.vm.network "forwarded_port", guest: 80, host: 8080

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # 
  config.vm.network "private_network", ip: "172.25.250.9"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  # config.vm.provider "virtualbox" do |vb|
  #   # Display the VirtualBox GUI when booting the machine
  #   vb.gui = true
  #
  #   # Customize the amount of memory on the VM:
  #   vb.memory = "1024"
  # end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
  # documentation for more information about their specific syntax and use.

  config.vm.provision "file", source: "../_config/.ssh/server_root_id_rsa", destination: "/tmp/server_root_id_rsa"

  config.vm.provision "shell" do |s|
    ssh_priv_key = File.readlines("../_config/.ssh/server_root_id_rsa")
    s.inline = <<-SHELL
      dnf install -y epel-release
      dnf update
      dnf install -y ansible
      COUNT=$(grep -c "172.25.250.10" /etc/hosts)
      if [ $COUNT -eq 0 ]
      then
        echo "172.25.250.10 servera.lab.example.com servera" >> /etc/hosts 
        echo "172.25.250.11 serverb.lab.example.com serverb" >> /etc/hosts 
        echo "172.25.250.12 serverc.lab.example.com serverc" >> /etc/hosts 
        echo "172.25.250.13 serverd.lab.example.com serverd" >> /etc/hosts 
      fi
      if [ -f /tmp/server_root_id_rsa ] 
      then
        [ -d /root/.ssh ] || mkdir /root/.ssh 
        [ -f /root/.ssh/id_rsa ] || mv /tmp/server_root_id_rsa /root/.ssh/id_rsa 
      fi 
      for i in 10 11 12 13
      do 
        ssh-keyscan 172.25.250.$i
      done 
    SHELL
  end



end
